# @package app
meta:
  model: 'siglip'
  crop_size: 512
  pred_depth: 6
  pred_emb_dim: 384
  use_bfloat16: false
  if_pred_pe: false
  n_layer: 3
  feat_normed: false
  loss_mode: 'l2'
  loss_config:
    margin: 1.0
    tau: 0.1
    lam1: 1.0 # Margin
    lam3: 1.0 # Graph
    lam4: 1.0 # Energy

logging:
  folder: logs/${data.data_name}/${app.meta.model}${oc.select:diy_name,""}
  write_tag: train
